global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'geth'
    metrics_path: '/debug/metrics/prometheus'
    static_configs:
      - targets: ['geth:6060']
  - job_name: 'nimbus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nimbus:8008']  
